### ISSUE TITLE
Comments between Nav menu <li> elements break the nav dropdowns

### ISSUE THREAD

**Issue by Raoch** [coreui/coreui#145] opened 2020-08-18 12:12 UTC
I'm trying to use CoreUI  (free) with .NET Blazor, Blazor inserts comments between every element to help with rendering and I believe this is breaking the nav bar on CoreUI, specifically the drop down doesnt work. I have a JSBin example at the bottom of this post.

On nav item click it gets all sibling elements and tries to get the classList of them without checking they are a valid element, hence throws an exception when trying to access classlist.contains on a comment. Just to test I edited the JS in dev tools toggleDropDown() method to exclude comments (added extra condition to if: && t.nodeName != '#comment') and it seemed to fix it, until i refreshed of course. 
from 

`
if (Default$9.dropdownAccordion === true) {

        this._getAllSiblings(toggler.parentElement).forEach(function (element) {

          if (element !== toggler.parentNode) {

            if (element.classList.contains(CLASS_NAME_NAV_DROPDOWN)) {

              element.classList.remove(CLASS_NAME_SHOW$6);
            }
          }
        });
      }
`
to 

`if (Default$9.dropdownAccordion === true) {

        this._getAllSiblings(toggler.parentElement).forEach(function (element) {

          if (element !== toggler.parentNode && element.nodeName != '#comment') {

            if (element.classList.contains(CLASS_NAME_NAV_DROPDOWN)) {

              element.classList.remove(CLASS_NAME_SHOW$6);
            }
          }
        });
      }`
Any assistance with this is much appreciated, happy to raise a pull request if I can get some guidance on this.

Details:
Using Windows 10
Tested on Chrome 84.0 and Firefox 79.0

**JSBin Example:**
https://jsbin.com/zizemis/edit?html,output

Old Codepen example(this example works but if you inspect can see that Codepen has removed the commnents):
https://codepen.io/JRoachBT/pen/poybwrz
Screenshot of debugging
![image](https://user-images.githubusercontent.com/20504130/90435084-62906c80-e0c6-11ea-9c69-3f5a11d7d869.png)

Reproduce Steps:
Create new Blazor project in visual studio
Add CoreUI Packages
Update layout to use CoreUI
Click any nav bar dropdown item

Many Thanks,

Josh

**Comment by mrholek** [comment] 2020-08-18 19:56
Can you try this code

```js
      if (Default$9.dropdownAccordion === true) {
        this._getAllSiblings(toggler.parentElement, function (element) {
          return Boolean(element.classList.contains(CLASS_NAME_NAV_DROPDOWN));
        }).forEach(function (element) {
          if (element !== toggler.parentNode) {
            if (element.classList.contains(CLASS_NAME_NAV_DROPDOWN)) {
              element.classList.remove(CLASS_NAME_SHOW$6);
            }
          }
        });
      }
```

**Comment by Raoch** [comment] 2020-08-18 20:04
Thanks for reply, tried the code and get the same errror, seems it is still trying to access .classList on the comment elements
![image](https://user-images.githubusercontent.com/20504130/90560061-72778180-e196-11ea-853b-8506186eafe7.png)

**Comment by mrholek** [comment] 2020-08-18 20:10
One more try

```js
    _proto._getAllSiblings = function _getAllSiblings(element, filter) {
      var siblings = [];
      element = element.parentNode.firstChild;

      do {
        if (element.nodeType === 3) {
          continue; // text node
        }

        if (element.nodeType === 8) {
          continue; // comment node
        }

        if (!filter || filter(element)) {
          siblings.push(element);
        } // eslint-disable-next-line no-cond-assign

      } while (element = element.nextSibling);

      return siblings;
    };
```

**Comment by Raoch** [comment] 2020-08-18 20:26
This seems to work now thanks a lot! Will this be change be applied to the main branch?

Also this might be better in its own issue as i'm not sure its related but sometimes on page load the dropdowns don't work, no exception thrown but nothing happens on click, is this anything you've come across?

**Comment by mrholek** [comment] 2020-08-18 20:32
This fix will be available in the next release. 

Can you try to reproduce the issue with dropdowns?

**Comment by Raoch** [comment] 2020-08-18 21:01
Awesome. I'm struggling to reproduce the error in codepen/JSBin which is leading me to believe its to do with Blazor, I have a fresh project with the issue here:
https://github.com/Raoch/TestTemplateNavError

**Comment by mrholek** [comment] 2020-09-02 20:18
Fixed in v3.3.0

**Closed** 2020-09-02 20:18 UTC

**Comment by Raoch** [comment] 2020-09-14 16:14
Will this fix also be available in core-ui bootstrap template?

**Comment by aquariens** [comment] 2020-11-21 17:14
> This seems to work now thanks a lot! Will this be change be applied to the main branch?

Hi, Is it possible for you to share a minimal blazor project with dropdown working? I tried the workaround but doesn't seems to be working. I am using CoreUI free with blazor server app.

Thanks,
