### ISSUE TITLE
Sidebar Minimizer Bug

### ISSUE THREAD

**Issue by nessimabadi** [coreui/coreui#12] opened 2018-05-25 14:48 UTC
When there's many items in the sidebar, the sidebar minimizer does not appear and the sidebar is not scrollable.

**Comment by syedzahed** [comment] 2018-09-11 07:31
Any help would be appreciated :)

**Comment by xidedix** [comment] 2018-09-26 11:45
hi @nessimabadi @syedzahed 
"sidebar-minimizer does not appear" issue has been fixed with `^2.0.9`
please update and let us know if this works for you

**Comment by nessimabadi** [comment] 2018-09-28 14:22
Hi,
With the new update (^2.0.9) the "sidebar-minimizer does not appear" issue has been fixed, tested it and it worked.

It is still not scrollable when minimized.

**Comment by xidedix** [comment] 2018-09-28 14:31
hi @nessimabadi thanks for the verifying
sidebar-minimized is not scrollable by design at the moment

**Comment by xidedix** [comment] 2018-10-10 12:41
I'm closing this since it appears to be inactive or fixed/answered above. Please comment/reopen if you feel the issue has not been resolved.

**Closed by xidedix** 2018-10-10 12:41 UTC
Labels: bug
